# Generated by Django 3.2.9 on 2021-12-05 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('time_available', models.CharField(choices=[('9am', '9am - 10am'), ('10am', '10am - 11am'), ('11am', '11am - 12pm'), ('12am', '12pm - 1pm'), ('1pm', '1pm - 2pm'), ('2pm', '2pm - 3pm'), ('3pm', '3pm - 4pm')], max_length=4)),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booker.speciality')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField()),
                ('time_selected', models.CharField(max_length=255)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booker.doctor')),
            ],
        ),
    ]
