# Generated by Django 3.2.9 on 2021-12-05 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='time_available',
        ),
    ]
